// auth
export const AUTHENTICATED = 'AUTHENTICATED'

// users
export const RECEIVE_USERS = 'RECEIVE_USERS'
export const RECEIVE_USER = 'RECEIVE_USER'

// orders
export const RECEIVE_ORDERS = 'RECEIVE_ORDERS'
export const RECEIVE_SINGLE_ORDER = 'RECEIVE_SINGLE_ORDER'

// products
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
export const RECEIVE_PRODUCT = 'RECEIVE_PRODUCT'

// reviews

export const RECEIVE_SINGLE_PRODUCT_REVIEWS = 'RECEIVE_SINGLE_PRODUCT_REVIEWS'
export const RECEIVE_REVIEW = 'RECEIVE_REVIEW'
