// auth
export const AUTHENTICATED = 'AUTHENTICATED'

// users
export const RECEIVE_USERS = 'RECEIVE_USERS'
export const RECEIVE_USER = 'RECEIVE_USER'

// orders
export const RECEIVE_ORDERS = 'RECEIVE_ORDERS'
export const RECEIVE_SINGLE_ORDER = 'RECEIVE_SINGLE_ORDER'
export const RECEIVE_CURRENT_ORDER = 'RECEIVE_CURRENT_ORDER'
export const ADD_PRODUCT_TO_ORDER = 'ADD_PRODUCT_TO_ORDER'
export const CHANGE_QUANTITY_OF_PRODUCT = 'CHANGE_QUANTITY_OF_PRODUCT'
export const REMOVE_PRODUCT_FROM_ORDER = 'REMOVE_PRODUCT_FROM_ORDER'
export const ADD_SHIPPING_ADDRESS = 'ADD_SHIIPING_ADDRESS'
export const CHANGE_SHIPPING_ADDRESS = 'CHANGE_SHIPPING_ADDRESS'
export const ADD_BILLING_ADDRESS = 'ADD_BILLING_ADDRESS'
export const CHANGE_BILLING_ADDRESS = 'CHANGE_BILLING_ADDRESS'
export const CHECKOUT = 'CHECKOUT'

// products
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'
export const RECEIVE_PRODUCT = 'RECEIVE_PRODUCT'

// reviews

export const RECEIVE_SINGLE_PRODUCT_REVIEWS = 'RECEIVE_SINGLE_PRODUCT_REVIEWS'
export const RECEIVE_REVIEW = 'RECEIVE_REVIEW'

// categories
export const SET_CURRENT_CATEGORY = 'SET_CURRENT_CATEGORY'